runtime: nodejs14 # or another supported version
service: default
instance_class: F2

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

vpc_access_connector:
  name: "projects/mailsenderproject-332310/locations/europe-west1/connectors/vpc-ac"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
