services:
  app:
    entrypoint: ["/bin/sh", "entrypoint.sh"]
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD:-secret}@postgres:${DB_PORT}/${DB_DATABASE}
      NODE_ENV: ${APP_ENV}
    ports:
      - '3000:3000'
      - '5555:5555'
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    networks:
      former_default:


  postgres:
    image: postgres
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - postgres:/data/postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
      retries: 3
      timeout: 5s
    networks:
      former_default:


volumes:
  postgres:


networks:
  former_default:
    external: true